"""Persistenz. Eine SQLite-Datei unter DATA_DIR/index/mpb.db. Repositories als Protokolle.

    catalog.py : CatalogRepo  (documents, chunks)         — Plattform
    runs.py    : RunRepo, EscalationRepo                   — Use Case
    audit.py   : AuditRepo (append-only audit.jsonl)       — beide
"""
from __future__ import annotations
from typing import Protocol, Iterable
from mpb.types import Chunk, Run, Project, Assessment, Escalation, AuditEvent


class CatalogRepo(Protocol):
    def upsert_document(self, doc_id: str, meta: dict) -> None: ...
    def get_document(self, doc_id: str) -> dict | None: ...
    def list_documents(self) -> list[dict]: ...
    def replace_chunks(self, doc_id: str, chunks: Iterable[Chunk]) -> None: ...
    def chunks_for(self, doc_id: str) -> list[Chunk]: ...
    def all_chunks(self, status: str = "active") -> list[Chunk]: ...
    def update_acl(self, doc_id: str, domain: str, classification: str, allow: list[str], published: bool, acl_hash: str) -> None: ...
    def set_status(self, doc_id: str, status: str) -> None: ...


class RunRepo(Protocol):
    def save_run(self, run: Run) -> None: ...
    def get_run(self, run_id: str) -> Run | None: ...
    def save_project(self, project: Project) -> None: ...
    def projects_for(self, run_id: str) -> list[Project]: ...
    def save_assessment(self, a: Assessment) -> None: ...
    def assessments_for(self, run_id: str, project_id: str | None = None) -> list[Assessment]: ...


class EscalationRepo(Protocol):
    def save(self, e: Escalation) -> None: ...
    def get(self, escalation_id: str) -> Escalation | None: ...
    def list_open(self, approver: str | None = None) -> list[Escalation]: ...
    def grants(self, run_id: str) -> dict[str, str]: ...   # doc_id -> principal, nur approved & nicht abgelaufen


class AuditRepo(Protocol):
    def append(self, event: AuditEvent) -> None: ...
    def tail(self, n: int = 50) -> list[AuditEvent]: ...
